/**
 * Ahmedabad (Gujarat) delivery areas with their PIN codes.
 * Only Ahmedabad city + its immediate suburbs are serviceable.
 */
export type AreaEntry = { area: string; pincode: string; zone: "West" | "East" | "North" | "South" | "Central" };

export const AHMEDABAD_AREAS: AreaEntry[] = [
  { area: "Lal Darwaja", pincode: "380001", zone: "Central" },
  { area: "Bhadra / Panchkuva", pincode: "380001", zone: "Central" },
  { area: "Kalupur", pincode: "380002", zone: "Central" },
  { area: "Dariapur", pincode: "380001", zone: "Central" },
  { area: "Shahibaug", pincode: "380004", zone: "Central" },
  { area: "Asarwa", pincode: "380016", zone: "East" },
  { area: "Saraspur", pincode: "380018", zone: "East" },
  { area: "Rakhial", pincode: "380023", zone: "East" },
  { area: "Amraiwadi", pincode: "380026", zone: "East" },
  { area: "Bapunagar", pincode: "380024", zone: "East" },
  { area: "Nikol", pincode: "382350", zone: "East" },
  { area: "Naroda", pincode: "382330", zone: "East" },
  { area: "Naroda GIDC", pincode: "382330", zone: "East" },
  { area: "Kubernagar", pincode: "382340", zone: "East" },
  { area: "Sardarnagar", pincode: "382475", zone: "East" },
  { area: "Odhav", pincode: "382415", zone: "East" },
  { area: "Vastral", pincode: "382418", zone: "East" },
  { area: "Ramol", pincode: "382449", zone: "East" },
  { area: "Vatva", pincode: "382440", zone: "South" },
  { area: "Vatva GIDC", pincode: "382445", zone: "South" },
  { area: "Isanpur", pincode: "382443", zone: "South" },
  { area: "Ghodasar", pincode: "380050", zone: "South" },
  { area: "Vejalpur", pincode: "380051", zone: "West" },
  { area: "Maninagar", pincode: "380008", zone: "South" },
  { area: "Khokhra", pincode: "380008", zone: "South" },
  { area: "Danilimda", pincode: "380028", zone: "South" },
  { area: "Behrampura", pincode: "380022", zone: "South" },
  { area: "Jamalpur", pincode: "380001", zone: "Central" },
  { area: "Paldi", pincode: "380007", zone: "West" },
  { area: "Ambawadi", pincode: "380006", zone: "West" },
  { area: "Ellisbridge", pincode: "380006", zone: "West" },
  { area: "Navrangpura", pincode: "380009", zone: "West" },
  { area: "C G Road", pincode: "380009", zone: "West" },
  { area: "Vasna", pincode: "380007", zone: "West" },
  { area: "Sarkhej", pincode: "382210", zone: "West" },
  { area: "Juhapura", pincode: "380055", zone: "West" },
  { area: "Makarba", pincode: "380051", zone: "West" },
  { area: "Prahlad Nagar", pincode: "380015", zone: "West" },
  { area: "Satellite", pincode: "380015", zone: "West" },
  { area: "Jodhpur (Satellite)", pincode: "380015", zone: "West" },
  { area: "Anandnagar", pincode: "380015", zone: "West" },
  { area: "Bodakdev", pincode: "380054", zone: "West" },
  { area: "Thaltej", pincode: "380059", zone: "West" },
  { area: "Sola", pincode: "380060", zone: "West" },
  { area: "Science City Road", pincode: "380060", zone: "West" },
  { area: "Ghatlodia", pincode: "380061", zone: "West" },
  { area: "Chandlodia", pincode: "382481", zone: "North" },
  { area: "Nirnaynagar", pincode: "382481", zone: "North" },
  { area: "Ranip", pincode: "382480", zone: "North" },
  { area: "New Ranip", pincode: "382470", zone: "North" },
  { area: "Naranpura", pincode: "380013", zone: "West" },
  { area: "Vadaj", pincode: "380013", zone: "West" },
  { area: "New Vadaj", pincode: "380013", zone: "West" },
  { area: "Usmanpura", pincode: "380013", zone: "West" },
  { area: "Stadium / Navjivan", pincode: "380014", zone: "West" },
  { area: "Memnagar", pincode: "380052", zone: "West" },
  { area: "Gurukul", pincode: "380052", zone: "West" },
  { area: "Bopal", pincode: "380058", zone: "West" },
  { area: "South Bopal", pincode: "380058", zone: "West" },
  { area: "Shela", pincode: "380058", zone: "West" },
  { area: "Ghuma", pincode: "380058", zone: "West" },
  { area: "Chharodi", pincode: "382481", zone: "West" },
  { area: "Gota", pincode: "382481", zone: "North" },
  { area: "Jagatpur", pincode: "382481", zone: "North" },
  { area: "Motera", pincode: "380005", zone: "North" },
  { area: "Sabarmati", pincode: "380005", zone: "North" },
  { area: "Chandkheda", pincode: "382424", zone: "North" },
  { area: "New CG Road (Chandkheda)", pincode: "382424", zone: "North" },
  { area: "Zundal", pincode: "382421", zone: "North" },
  { area: "Koteshwar", pincode: "380005", zone: "North" },
  { area: "Nava Naroda", pincode: "382345", zone: "East" },
  { area: "Krishnanagar", pincode: "382346", zone: "North" },
  { area: "Meghaninagar", pincode: "380016", zone: "East" },
  { area: "Girdharnagar", pincode: "380004", zone: "Central" },
  { area: "Dudheshwar", pincode: "380004", zone: "Central" },
  { area: "Shahpur", pincode: "380001", zone: "Central" },
  { area: "Khadia", pincode: "380001", zone: "Central" },
  { area: "Raipur", pincode: "380001", zone: "Central" },
  { area: "Astodia", pincode: "380001", zone: "Central" },
  { area: "Kankaria", pincode: "380022", zone: "South" },
  { area: "Hatkeshwar", pincode: "380026", zone: "East" },
  { area: "CTM (Char Rasta)", pincode: "380026", zone: "East" },
  { area: "Vastrapur", pincode: "380015", zone: "West" },
  { area: "IIM / Panjrapole", pincode: "380015", zone: "West" },
  { area: "Ambli", pincode: "380058", zone: "West" },
  { area: "SG Highway (Sindhu Bhavan)", pincode: "380054", zone: "West" },
  { area: "Shilaj", pincode: "380059", zone: "West" },
  { area: "Shantigram", pincode: "382421", zone: "North" },
  { area: "Nava Vadaj", pincode: "380013", zone: "West" },
  { area: "Naroda Road", pincode: "382345", zone: "East" },
  { area: "Kathwada", pincode: "382430", zone: "East" },
  { area: "Vinzol", pincode: "382445", zone: "South" },
  { area: "Narol", pincode: "382405", zone: "South" },
  { area: "Lambha", pincode: "382405", zone: "South" },
  { area: "Shahwadi", pincode: "382405", zone: "South" },
];

/** Unique, sorted list of serviceable Ahmedabad PIN codes. */
export const AHMEDABAD_PINCODES = Array.from(
  new Set(AHMEDABAD_AREAS.map((a) => a.pincode)),
).sort();

export function areasForPincode(pincode: string) {
  return AHMEDABAD_AREAS.filter((a) => a.pincode === pincode.trim());
}

export function findArea(name: string) {
  return AHMEDABAD_AREAS.find((a) => a.area.toLowerCase() === name.trim().toLowerCase());
}
